### ISSUE TITLE
Inject Osris hack and the game crash.

### ISSUE THREAD

**Issue by amrkamal2025** [BohanRen/BobHCSGOInjector#6]
Hi, 

first, thank you for sharing this project,  second thing when I try to inject the hack into csgo the game crash, so I am wondering if there is any update or anything needed to make it work now, because I used another inejctor the game worked and not crash.

Thanks in advance.

**Comment by Kian738** [comment]
Is it working with other injectors

**Comment by BohanRen** [comment]
I try to emulate your situation, and I inject successfully with the latest Osiris.dll
![QQ截图20210615231629](https://user-images.githubusercontent.com/23572936/122079318-e07ceb80-ce2f-11eb-90f6-5e651c1a51ed.png)
